[MAIN]
is_local = True
provider_name = ollama
# Options: ollama, lm-studio, server, openai, google, deepseek, huggingface, togetherAI, openrouter, sapient_hrm, colab, auto
provider_model = deepseek-r1:14b
provider_server_address = 127.0.0.1:11434
# For colab, use the ngrok url (e.g. http://xxxx.ngrok.io)
agent_name = Jarvis
recover_last_session = False
save_session = False
speak = False
listen = False
jarvis_personality = False
languages = en
[BROWSER]
headless_browser = True
stealth_mode = False